apiVersion: apps/v1
kind: Deployment
metadata:
      name:  cricketer-info-deployment
      labels:
          app: cricketer-info
spec:
     selector:
         matchLabels:
            app: cricketer-info
     replicas:
     template:
           metadata:
                 labels:
                     app: cricketer-info
           spec:
              containers:
                  - name: cricketer-info
                    image: cricketer-info:1.0
                    imagePullPolicy: IfNotPresent
                    ports: 
                       - containerPort: 8080
 